// Automatic FlutterFlow imports
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'index.dart'; // Imports other custom actions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

Future<String?> getLanguageName(String? languageCode) async {
  if (languageCode == null) return null;

  final languageData = [
    {"code": "an", "name": "Aragonese"},
    {"code": "ak", "name": "Akan"},
    {"code": "cr", "name": "Cree"},
    {"code": "az", "name": "Azerbaijani"},
    {"code": "cs", "name": "Czech"},
    {"code": "aa", "name": "Afar"},
    {"code": "br", "name": "Breton"},
    {"code": "af", "name": "Afrikaans"},
    {"code": "bo", "name": "Tibetan"},
    {"code": "ce", "name": "Chechen"},
    {"code": "kw", "name": "Cornish"},
    {"code": "fo", "name": "Faroese"},
    {"code": "la", "name": "Latin"},
    {"code": "ng", "name": "Ndonga"},
    {"code": "sc", "name": "Sardinian"},
    {"code": "ti", "name": "Tigrinya"},
    {"code": "tn", "name": "Tswana"},
    {"code": "tr", "name": "Turkish"},
    {"code": "pa", "name": "Punjabi"},
    {"code": "et", "name": "Estonian"},
    {"code": "fr", "name": "French"},
    {"code": "ha", "name": "Hausa"},
    {"code": "is", "name": "Icelandic"},
    {"code": "li", "name": "Limburgish"},
    {"code": "ln", "name": "Lingala"},
    {"code": "ss", "name": "Swati"},
    {"code": "ab", "name": "Abkhazian"},
    {"code": "sh", "name": "Serbo-Croatian"},
    {"code": "eu", "name": "Basque"},
    {"code": "fy", "name": "Frisian"},
    {"code": "ja", "name": "Japanese"},
    {"code": "oj", "name": "Ojibwa"},
    {"code": "or", "name": "Oriya"},
    {"code": "pi", "name": "Pali"},
    {"code": "su", "name": "Sundanese"},
    {"code": "th", "name": "Thai"},
    {"code": "ig", "name": "Igbo"},
    {"code": "id", "name": "Indonesian"},
    {"code": "kk", "name": "Kazakh"},
    {"code": "ki", "name": "Kikuyu"},
    {"code": "ug", "name": "Uighur"},
    {"code": "ve", "name": "Venda"},
    {"code": "rw", "name": "Kinyarwanda"},
    {"code": "mi", "name": "Maori"},
    {"code": "nv", "name": "Navajo"},
    {"code": "hi", "name": "Hindi"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "sg", "name": "Sango"},
    {"code": "sk", "name": "Slovak"},
    {"code": "sr", "name": "Serbian"},
    {"code": "ty", "name": "Tahitian"},
    {"code": "xh", "name": "Xhosa"},
    {"code": "ar", "name": "Arabic"},
    {"code": "co", "name": "Corsican"},
    {"code": "bi", "name": "Bislama"},
    {"code": "eo", "name": "Esperanto"},
    {"code": "hz", "name": "Herero"},
    {"code": "fi", "name": "Finnish"},
    {"code": "iu", "name": "Inuktitut"},
    {"code": "lv", "name": "Latvian"},
    {"code": "it", "name": "Italian"},
    {"code": "nl", "name": "Dutch"},
    {"code": "kn", "name": "Kannada"},
    {"code": "sa", "name": "Sanskrit"},
    {"code": "sq", "name": "Albanian"},
    {"code": "tl", "name": "Tagalog"},
    {"code": "lb", "name": "Letzeburgesch"},
    {"code": "ts", "name": "Tsonga"},
    {"code": "ml", "name": "Malayalam"},
    {"code": "vo", "name": "Volap k"},
    {"code": "zu", "name": "Zulu"},
    {"code": "os", "name": "Ossetic"},
    {"code": "sm", "name": "Samoan"},
    {"code": "za", "name": "Zhuang"},
    {"code": "bn", "name": "Bengali"},
    {"code": "cu", "name": "Slavic"},
    {"code": "ga", "name": "Irish"},
    {"code": "gv", "name": "Manx"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "jv", "name": "Javanese"},
    {"code": "kr", "name": "Kanuri"},
    {"code": "km", "name": "Khmer"},
    {"code": "ky", "name": "Kirghiz"},
    {"code": "na", "name": "Nauru"},
    {"code": "nr", "name": "Ndebele"},
    {"code": "oc", "name": "Occitan"},
    {"code": "ro", "name": "Romanian"},
    {"code": "ru", "name": "Russian"},
    {"code": "hy", "name": "Armenian"},
    {"code": "ch", "name": "Chamorro"},
    {"code": "xx", "name": "No Language"},
    {"code": "ba", "name": "Bashkir"},
    {"code": "gl", "name": "Galician"},
    {"code": "io", "name": "Ido"},
    {"code": "lu", "name": "Luba-Katanga"},
    {"code": "mh", "name": "Marshall"},
    {"code": "mg", "name": "Malagasy"},
    {"code": "mo", "name": "Moldavian"},
    {"code": "mn", "name": "Mongolian"},
    {"code": "nd", "name": "Ndebele"},
    {"code": "no", "name": "Norwegian"},
    {"code": "pl", "name": "Polish"},
    {"code": "sw", "name": "Swahili"},
    {"code": "tg", "name": "Tajik"},
    {"code": "to", "name": "Tonga"},
    {"code": "wa", "name": "Walloon"},
    {"code": "yi", "name": "Yiddish"},
    {"code": "en", "name": "English"},
    {"code": "as", "name": "Assamese"},
    {"code": "gd", "name": "Gaelic"},
    {"code": "kl", "name": "Kalaallisut"},
    {"code": "my", "name": "Burmese"},
    {"code": "qu", "name": "Quechua"},
    {"code": "sn", "name": "Shona"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "fa", "name": "Persian"},
    {"code": "ka", "name": "Georgian"},
    {"code": "gu", "name": "Gujarati"},
    {"code": "av", "name": "Avaric"},
    {"code": "ae", "name": "Avestan"},
    {"code": "gn", "name": "Guarani"},
    {"code": "mt", "name": "Maltese"},
    {"code": "ne", "name": "Nepali"},
    {"code": "sv", "name": "Swedish"},
    {"code": "tt", "name": "Tatar"},
    {"code": "wo", "name": "Wolof"},
    {"code": "cn", "name": "Cantonese"},
    {"code": "cv", "name": "Chuvash"},
    {"code": "da", "name": "Danish"},
    {"code": "dz", "name": "Dzongkha"},
    {"code": "ny", "name": "Nyanja"},
    {"code": "rn", "name": "Rundi"},
    {"code": "st", "name": "Sotho"},
    {"code": "tk", "name": "Turkmen"},
    {"code": "uz", "name": "Uzbek"},
    {"code": "vi", "name": "Vietnamese"},
    {"code": "el", "name": "Greek"},
    {"code": "ca", "name": "Catalan"},
    {"code": "cy", "name": "Welsh"},
    {"code": "de", "name": "German"},
    {"code": "ks", "name": "Kashmiri"},
    {"code": "ms", "name": "Malay"},
    {"code": "nb", "name": "Norwegian Bokm l"},
    {"code": "rm", "name": "Raeto-Romance"},
    {"code": "si", "name": "Sinhalese"},
    {"code": "es", "name": "Spanish"},
    {"code": "te", "name": "Telugu"},
    {"code": "tw", "name": "Twi"},
    {"code": "ps", "name": "Pushto"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "ik", "name": "Inupiaq"},
    {"code": "ko", "name": "Korean"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "om", "name": "Oromo"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "ur", "name": "Urdu"},
    {"code": "be", "name": "Belarusian"},
    {"code": "he", "name": "Hebrew"},
    {"code": "hr", "name": "Croatian"},
    {"code": "mr", "name": "Marathi"},
    {"code": "ta", "name": "Tamil"},
    {"code": "yo", "name": "Yoruba"},
    {"code": "yi", "name": "Yiddish"}
  ];

  var english;
  final language = languageData.firstWhere(
      (lang) => lang['code'] == languageCode,
      orElse: () => english);

  // ignore: unnecessary_null_comparison
  return language != null ? language['name'] : null;
}
